version: '3.4'

services:

  #web.gw:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
  #    - "9001:80"
  #    - "9000:443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=productdb;Port=5433;Database=ProductDb;Username=admin;Password=duch;"
      - "IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}"
    ports:
      - "8095:80"
    depends_on:
      - product.db

  product.db:
    container_name: productdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=duch
      - POSTGRES_DB=ProductDb
    restart: always
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - product_db_data:/var/lib/postgresql/data 

  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=userdb;Port=5434;Database=UserDb;Username=admin;Password=duch;"
    ports:
      - "8096:80"

  user.db:
    container_name: userdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=duch
      - POSTGRES_DB=UserDb
    restart: always
    ports:
      - "5434:5434"
    command: -p 5434
    volumes:
      - user_db_data:/var/lib/postgresql/data 

  projectdetail.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=projectdetaildb;Database=ProjectDb;User Id=sa;Password=SwN12345678;"
    ports:
      - "8093:80"
    depends_on:
      - projectdetail.db

  projectdetail.db:
    container_name: projectdetaildb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1431:1433"

  #mongo.db:
  #  container_name: mongodbservice
  #  restart: always
  #  ports:
  #    - 27017:27017  
  #  volumes:
  #    - ${WEBAPP_STORAGE_HOME}/site:/data/db

  #basketdb:
  #  container_name: basketdb
  #  restart: always    
  #  ports:
  #      - "6379:6379"
  
  #discount.db:
  #  container_name: discountdb
  #  environment:
  #    - POSTGRES_USER=admin
  #    - POSTGRES_PASSWORD=duch
  #    - POSTGRES_DB=DiscountDb
  #  restart: always
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data 

  #order.db:
  #  container_name: orderdb
  #  environment:
  #      SA_PASSWORD: "SwN12345678"
  #      ACCEPT_EULA: "Y"
  #  restart: always
  #  ports:
  #      - "1433:1433"

  #customer.db:
  #  container_name: customerdb
  #  environment:
  #      SA_PASSWORD: "SwN12345678"
  #      ACCEPT_EULA: "Y"
  #  restart: always
  #  ports:
  #      - "1432:1433"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@patrikduch.com
      - PGADMIN_DEFAULT_PASSWORD=duch
    restart: always
    ports:
      -  "5050:80"
    volumes:
      -  pgadmin_data:/root/.pgadmnin 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"   # RabbitMQ server for accessing and publishing new messages
        - "15672:15672" # Access to the RabbitMQ portal
  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    hostname: rabbitmq  # How RabbitMQ stored data internally, if it's not specified then it gets random value
 
  #web.spa:
  #  container_name: webspa
  #  depends_on:
  #    - realtimetransmission.api
  #  environment:
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #    - "SignalRSettings__ConnectionString=http://localhost:8090"
  #  ports:
  #    - "81:80"
  #    - "443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  #web.mvc:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "8081:80"

  #basket.api:
  #  container_name: basketapi
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "CacheSettings__ConnectionString=basketdb:6379"
  #    - "GrpcSettings__DiscountUrl=http://discountgrpc"
  #  depends_on:
  #      - basketdb
  #  ports:
  #    - "8082:80"

  #catalog.api:
  #  container_name: catalogapi
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "MongoDbSettings__Host=mongodbservice"
  #    - "MongoDbSettings__CollectionName=products"
  #    - "MongoDbSettings__DatabaseName=ProductsDb"
  #    - "MongoDbSettings__Port=27017"
  #    - "ServiceSettings__ServiceName=Catalog"
  #  ports:
  #    - "8083:80"

  #discount.grpc:
  #  container_name: discountgrpc
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=duch;"
  #  ports:
  #    - "8085:80"
  #
  #  depends_on:
  #    - discount.db

  #discount.api:
  # environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=duch;"
  #  ports:
  #    - "8086:80"

  #  depends_on:
  #    - discount.db
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  #gamecatalog.api:
  #  container_name: gamecatalogapi
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "MongoDbSettings__Host=mongodbservice"
  #    - "MongoDbSettings__CollectionName=items"
  #    - "MongoDbSettings__DatabaseName=ItemsDb"
  #    - "MongoDbSettings__Port=27017"
  #    - "ServiceSettings__ServiceName=GameCatalog"
  #    - "RabbitMqSettings__Host=amqp://guest:guest@rabbitmq:5672"
  #  ports:
  #    - "8087:80"

  #signalr.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "8088:80"

  #inventory.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "MongoDbSettings__Host=mongodbservice"
  #    - "MongoDbSettings__CollectionName=inventories"
  #    - "MongoDbSettings__DatabaseName=InventoryDb"
  #    - "MongoDbSettings__Port=27017"
  #    - "ServiceSettings__ServiceName=Inventory"
  #    - "RabbitMqSettings__Host=amqp://guest:guest@rabbitmq:5672"
  #  ports:
  #    - "8089:80"

  #realtimetransmission.api:
  #  container_name: realtimetransmissionapi
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "8090:80"

  #ordering.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "DatabaseSettings__ConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
  #  ports:
  #    - "8091:80"

  #  depends_on:
  #    - order.db

  #customer.api:
  #  environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - "DatabaseSettings__ConnectionString=Server=customerdb;Database=CustomerDb;User Id=sa;Password=SwN12345678;"
  #  ports:
  #    - "8092:80"
  #  depends_on:
  #    - customer.db
 


  identityauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "9091:80"
      - "9092:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  web.gw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"


  web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "1001:80"
      - "1000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
