apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  labels:
    app: product-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: productapi
          image:  netcoremicroservicesacr.azurecr.io/productapi:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 5Gi  
            limits:
              memory: 5Gi  
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  secretKeyRef:
                    name: product-api-secret
                    key: ConnectionString
            - name: IDENTITY_SERVER_URL
              valueFrom:
                  secretKeyRef:
                    name: product-api-secret
                    key: IDENTITY_SERVER_URL

      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  type: ClusterIP
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80