kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: productdb-storage
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuName: Standard_LRS
  kind: Managed
  cachingmode: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "productdb-storage"
  resources:
    requests:
      storage: 5Gi
      