apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: userapi
          image:  netcoremicroservicesacr.azurecr.io/userapi:1566
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  secretKeyRef:
                    name: user-api-secret
                    key: ConnectionString
            - name: IDENTITY_SERVER_URL
              valueFrom:
                  secretKeyRef:
                    name: user-api-secret
                    key: IDENTITY_SERVER_URL




      imagePullSecrets:
        - name: acr-secret