apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-mvc-deployment
  labels:
    app: web-mvc
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: web-mvc
  template:
    metadata:
      labels:
        app: web-mvc
    spec:
      containers:
        - name: web-mvc
          image:  netcoremicroservicesacr.azurecr.io/webmvc:v1
          imagePullPolicy: IfNotPresent
          
          ports:
            - containerPort: 80

      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-mvc-service
spec:
  type: LoadBalancer
  selector:
    app: web-mvc
  ports:
    - protocol: TCP
      port: 80